package cursor_trick;

import java.awt.AWTException;
import java.awt.MouseInfo;
import java.awt.Robot;
import java.awt.PointerInfo;
import java.awt.Point;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Gabriel Coronado
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */


    int time = 5000;
    Timer timer = new Timer(time, (ae) -> {
        mouseMover();
    });
    public Main() {
        initComponents();
        txtSecs.setEditable(true);
        cmdStart.setEnabled(false);
        cmdStop.setEnabled(false);
    }

    public void mouseMover(){

        try {
            Random random = new Random();
            PointerInfo a = MouseInfo.getPointerInfo();
            Point b = a.getLocation();
            int x = (int) b.getX();
            int y = (int) b.getY();
            Robot r = new Robot();
            int rnd = random.nextInt(5) - 2;
            r.mouseMove(x + rnd, y);
        } catch (AWTException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdStop = new javax.swing.JButton();
        cmdStart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdClose = new javax.swing.JButton();
        txtSecs = new javax.swing.JTextField();
        cmdOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pause.png"))); // NOI18N
        cmdStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStopActionPerformed(evt);
            }
        });
        jPanel1.add(cmdStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, 40));

        cmdStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/play.png"))); // NOI18N
        cmdStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStartActionPerformed(evt);
            }
        });
        jPanel1.add(cmdStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mouse Mover by Pichiño v1.0");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 190, 40));

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/exit.png"))); // NOI18N
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });
        jPanel1.add(cmdClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 150, 30));

        txtSecs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSecsKeyTyped(evt);
            }
        });
        jPanel1.add(txtSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 30));

        cmdOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ok_list.png"))); // NOI18N
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });
        jPanel1.add(cmdOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, 30));

        jLabel2.setText("Enter your timeframe in secs:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(342, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStopActionPerformed
        // TODO add your handling code here:
        System.out.println("STOPPED");
        timer.stop();
        cmdStart.setEnabled(false);
        cmdStop.setEnabled(false);
        txtSecs.setEditable(true);
        txtSecs.requestFocusInWindow();
        cmdOk.setEnabled(true);
    }//GEN-LAST:event_cmdStopActionPerformed

    private void cmdStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStartActionPerformed
        // TODO add your handling code here:
        cmdStop.setEnabled(true);
        cmdStart.setEnabled(false);
        timer.setInitialDelay(1000);
        timer.start();
        this.setState(this.ICONIFIED);

    }//GEN-LAST:event_cmdStartActionPerformed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void txtSecsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecsKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSecsKeyTyped

    private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
        // TODO add your handling code here:
        //if
        try {
            int tf = Integer.parseInt(txtSecs.getText().trim());
            if (tf > 180 || tf == 0) {
                JOptionPane.showMessageDialog(this, "Cannot be higher than 180 nor equal to 0.","ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
               time = tf*1000;
               timer.setDelay(time);
               cmdStart.setEnabled(true);
               txtSecs.setEditable(false);
               cmdOk.setEnabled(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Enter a valid number.","ERROR", JOptionPane.ERROR_MESSAGE);
            txtSecs.requestFocusInWindow();
        }

    }//GEN-LAST:event_cmdOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdOk;
    private javax.swing.JButton cmdStart;
    private javax.swing.JButton cmdStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtSecs;
    // End of variables declaration//GEN-END:variables
}
